### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by talhashoaib27** [meetmangukiya/instagram-scraper#10]
When I try to run it:

  File "instagram_scraper.py", line 25
    url = f'https://www.instagram.com/explore/tags/{tag}'
                                                        ^
SyntaxError: invalid syntax

**Comment by meetmangukiya** [comment]
Are you using python 3.6? This might be because of the format string, they are 3.6+ only.

**Comment by meetmangukiya** [comment]
Closing, reopen if still an issue.
