### ISSUE TITLE
No module named 'requests_html'

### ISSUE THREAD

**Issue by stefanocudini** [meetmangukiya/instagram-scraper#11]
After the pip install -r requirements.txt

```
Traceback (most recent call last):
  File "instagram_scraper.py", line 10, in <module>
    from requests_html import HTMLSession
ModuleNotFoundError: No module named 'requests_html'
```

**Comment by meetmangukiya** [comment]
that's odd, does `python -c "import requests_html"` work?

**Comment by stefanocudini** [comment]
https://github.com/meetmangukiya/instagram-scraper/blob/master/requirements.txt#L1

**Comment by meetmangukiya** [comment]
The package name is correct, just ensure that it is installed on your system. And the output of `pip install -r requirements.txt` should suggest that it was installed correctly.
