### ISSUE TITLE
Im a newb here... Im not sure where to put the tags for "sunset" and "20 pics.... 

### ISSUE THREAD

**Issue by CryptoRootz** [meetmangukiya/instagram-scraper#16]
Im a newb here and im not sure where to put the tags and count ? can some one give me a example ? the one is the description is not enough for me to get it ... i keep running into the same error

er.py", line 117, in <module>
    assert args.tags, "Enter tags to scrape! Use --tags option, see help."
AttributeError: 'Namespace' object has no attribute 'tags'

**Comment by meetmangukiya** [comment]
What is the exact command that you used? If you want to download 20 pics of sunset then the command would look something like this `python instagram-scraper.py --tags sunset --count 20`

**Comment by meetmangukiya** [comment]
Closing, reopen if still an issue.
